# Deployment to Render.com
name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$deploy_url" ]; then
            echo "RENDER_DEPLOY_HOOK_URL secret is not set"
            exit 1
          fi
          
          curl "$deploy_url"