# Linters, tests, and build
name: CI

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Node-ci-pipeline:
    # strategy:
    #   matrix:
    #     version: [20, 22]
    #     os: [ubuntu-latest, windows-latest]
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
        #  node-version: ${{ matrix.version }}
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build project
        run: npm run build

