name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Node-ci-pipeline:
    strategy:
      matrix:
        version: [20, 22]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.version }}
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build project
        run: npm run build
        
      # Deployment to Render.com
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: Node-ci-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$deploy_url" ]; then
            echo "RENDER_DEPLOY_HOOK_URL secret is not set"
            exit 1
          fi
          
          curl "$deploy_url"
